### ISSUE TITLE
Upgrade to memo v2

### ISSUE THREAD

**Issue by steveluscher** [solana-program/memo#1]
This appears to be built for the v1 memo program `Memo1UhkJRfHyvLMcVucJwxXeuD728EqVDDwQDxFMNo`. The program we want a modern client for is `MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr`.

https://github.com/solana-labs/solana-program-library/tree/master/memo/program

**Comment by lorisleiva** [comment]
Thanks for raising this! Will fix on Monday.

**Comment by lorisleiva** [comment]
Fixed in version `0.1.2`.
