### ISSUE TITLE
Keep the old spl-memo API

### ISSUE THREAD

**Issue by kevinheavey** [solana-program/memo#3]
The generated rust and ts clients don't have the same API as [spl-memo](https://github.com/solana-labs/solana-program-library/blob/master/memo/). If the new "official" clients are going to live here it would be nice for them to be drop-in replacements

**Comment by lorisleiva** [comment]
Hi there. Sorry they won't be. The new APIs are generated and compatible with the new web3.js (v2.x) which is a complete rewrite.

**Comment by kevinheavey** [comment]
What is the benefit of autogenerating a client for the _memo_ program?

**Comment by lorisleiva** [comment]
Consistency. ☺️

**Comment by kevinheavey** [comment]
fwiw i don't think that's a compelling reason for users to switch to the new package
